name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start Docker Compose
        run: |
          docker compose up -d
          echo "⏳ Waiting for containers to initialize..."
          sleep 20

      - name: Install curl inside web container
        run: docker compose exec -T web apt-get update && apt-get install -y curl

      - name: Run test inside web container
        run: docker compose exec -T web curl http://localhost:5000/api/users

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down
